params:
  dbPath: ./db
  parsingInterval: 60 # seconds
  # maxItemAmount: 40
  itemLifePeriod: 2592000 # seconds
recievers:
  - type: telegram
    token: 7004923945:AAEL8YLDdkFrLNGfFKFaNg3hzLwiCDg7QgI
    chatID: 460110156
  # - type: telegram
  #   token: 7004923945:AAEL8YLDdkFrLNGfFKFaNg3hzLwiCDg7QgI
  #   chatID: -4177220110
targets:
  - name: OLX_watch
    url: https://www.olx.ua/uk/moda-i-stil/naruchnye-chasy/
    query: '.css-u2ayx9 .css-z3gu2d'
    attr: href
    linkWithoutSchema: true
  # - name: SO_reactjs
  #   url: https://ru.stackoverflow.com/questions/tagged/reactjs
  #   query: '.s-post-summary--content-title .s-link'
  #   attr: href
  #   linkWithoutSchema: true
  # - url: https://www.scrapingcourse.com/ecommerce/
  #   query: '.woocommerce-LoopProduct-link'
  #   attr: href
