services:
  scraper:
    restart: unless-stopped
    build:
      context: ./scraper
      dockerfile: Dockerfile
    volumes:
      - ./config.yaml:/app/tmp/config.yaml
      - ./scraper:/app

  db:
    restart: unless-stopped
    volumes:
      - ./db/data:/data/db
