services:
  scraper:
    restart: unless-stopped
    build:
      context: ./scraper
      dockerfile: Dockerfile
      args:
        - GO_VERSION
    volumes:
      - ./scraper:/app
      - ./config.yaml:/app/tmp/config.yaml

  db:
    restart: unless-stopped
    volumes:
      - ./db/data:/data/db
