ARG GO_VERSION

FROM golang:${GO_VERSION}-alpine as builder

WORKDIR /app

COPY . .

RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o hora

FROM golang:${GO_VERSION}-alpine

WORKDIR /app

COPY --from=builder /app/hora .

CMD [ "./hora" ]
